version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: verbia-server
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=http://localhost:8080
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: verbia-client
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./client/default.conf:/etc/nginx/conf.d/default.conf:ro
